= Rust Fundamentals
Notes
:toc: auto

== Introduction 

* Fundamentals are important in rust.
* System programming language.
* Good for `Safety`, `Concurrency`, and `Speed`.

[quote, Wikipedia CONCURRENCY, https://en.wikipedia.org/wiki/Concurrency_(computer_science)]
In computer science, #concurrency# is the ability of different parts or units of a program, algorithm, or problem to be executed out-of-order or in partial order, without affecting the final outcome.

* `Python` can give you safety but not concurrency or speed.
* `C/C++` will give you speed and some concurrency but not safety.

https://github.com/CleanCut/ultimate_rust_crash_course [Github repo for exercises]

== Cargo 

* `Cargo` is a #package manager# for `Rust`. It is used to #search# for, #install# and manage packages that you want to use. It is also a #build system#, the #test runner#, and the #documentation generator#. Similar to _npn_, _pip_, and _make_.

* If you want to quickly create a project called *hello*, you can use the following command: `$ cargo new hello`. When you do `$ tree --noreport hello`, you will notice that the project has been created successfully. A config file `Cargo.toml` and a sorce directory `src` with the RUST `main.rs` file.

[plantuml, format=svg, opts="inline"]
----
hello
|_ Cargo.toml
|_ src
    |_ main.rs
----

[quote, Wikipedia TOML, https://en.wikipedia.org/wiki/TOML]
The name "TOML" is an acronym for "Tom's Obvious, Minimal Language" referring to its creator, Tom Preston-Werner.
TOML is a file format for configuration files. It is intended to be easy to read and write due to obvious semantics which aim to be "minimal", and is designed to map unambiguously to a dictionary. Its specification is open-source, and receives community contributions.